config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    sessions: 'users/sessions', registrations: 'users/registrations'
  }
  resources :topics, except: [:show]
  authenticated :user do
    root 'topics#available_topics'
  end
  root 'welcome#index'
  get '/trending_topics', to: 'topics#available_topics', as: 'available_topics'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
#
# Topic Model
#
# @author rashid
#
class Topic
  include Neo4j::ActiveNode
  property :name, type: String
  property :description, type: String
  property :hit, type: Integer
end

app/controllers/topics_controller.rb
#
# TopicsController
#
# @author rashid
#
class TopicsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json do
          render status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html do
          redirect_to topics_path, notice: 'Topic was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json do
          render status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html do
        redirect_to topics_url, notice: 'Topic was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  def available_topics
    @topics = Topic.all
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_topic
    @topic = Topic.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def topic_params
    params.require(:topic).permit(:name, :description, :hit)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(topic) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/available_topics.html.erb
<ul>
<% @topics.each do |topic| %>
  <li><%= topic.name %></li>
<% end %>
</ul>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Hits</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.name %></td>
        <td><%= topic.hit %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>